run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    # Base linters disabled for all projects.
    - funlen
    - gomnd  # Too picky. For example it says that 1000 (used in number of ms in one second) is a magic number.
    - exhaustivestruct # This linter is meant to be used only for special cases. It is not recommended to use it for all files in a project.
    - gci # Conflicts with gofumpt.
    - varnamelen # I think there is too many false-positive.
    - ireturn # Complain that interface A implementation method return an interface B... it's a requirement of interface A that is unavoidable.
    # Disable deprecated and replaced linter.
    - maligned
    - golint
    - interfacer
    - scopelint
    # We use maintidx to lint function complexity.
    - gocyclo
    - cyclop
    - gocognit

    # Project specific disable.
    - wrapcheck # too many error. Partially done and should be completed
    - goerr113 # Require to refactor how we return error. But would be useful
    # Requires to review all our tests. Should be done
    - paralleltest
    - tparallel
    - testpackage

linters-settings:
  nolintlint:
    # Ensure that nolint directives don't have a leading space.
    allow-leading-space: false
    # Require nolint directives to mention the specific linter being suppressed.
    require-specific: true

  tagliatelle:
    # Check struct tag name case.
    case:
      # Use the struct field name to check the name of the struct tag.
      rules:
        json: snake
        yaml: snake

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec

  include: # the list of ids of default excludes to include
    - EXC0005 # ineffective break statement
    - EXC0009 # create files/directories with minimum permissions
    # - EXC0011 # TODO: should have a package comment|comment should be of the form
    # - EXC0012 # TODO: exported var/functions should have a comment
    - EXC0013 # package comment should be of the form
    - EXC0014 # comment on exported var should be of the form

  max-issues-per-linter: 0
  max-same-issues: 0
