version: "2"

run:
  go: "1.24"
  timeout: 5m

linters:
  default: all
  disable:
    - cyclop # We use maintidx to lint function complexity.
    - err113
    - exhaustruct
    - funcorder # Would force us to reorganize hundreds of functions.
    - funlen
    - gocognit # We use maintidx to lint function complexity.
    - gocyclo # We use maintidx to lint function complexity.
    - interfacebloat # Warn when an interface has too many methods, not useful.
    - ireturn # Complain that interface A implementation method return an interface B... it's a requirement of interface A that is unavoidable.
    - mnd # Too picky. For example it says that 1000 (used in number of ms in one second) is a magic number.
    - nonamedreturns # Warn for every named return, not useful.
    - paralleltest
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: ioutil is deprecated starting with Go 1.16
    gomoddirectives:
      # List of allowed `replace` directives. Needed because go.mod doesn't support nolint comments.
      replace-allow-list:
        - cloud.google.com/go
    nolintlint:
      # Require nolint directives to mention the specific linter being suppressed.
      require-specific: true
    revive:
      rules:
        - name: exported
          disabled: true
    tagliatelle:
      case:
        # Use the struct field name to check the name of the struct tag.
        rules:
          json: snake
          yaml: snake

  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
