linters:
  enable-all: true
  disable:
    - lll
    - funlen
    - gomnd  # too picky. For example it say that 1000 (used in number of ms in one second) is a magic number.
    - testpackage # Require to review all our tests. Should be done
    - wrapcheck # too many error. Partially done and should be completed
    - nlreturn # too many error. Partially done and should be completed
    - goerr113 # Require to refactor how we return error. But would be useful
    - nestif # Too many error for now, which would require significant refactor.
    - exhaustivestruct # This linter is meant to be used only for special cases. It is not recommended to use it for all files in a project.
run:
  tests: false
