# Example Prometheus configuration using SquirrelDB as persitent storage

global:
  scrape_interval:     15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['node:9100']
  - job_name: 'squirreldb'
    static_configs:
    - targets: ['squirreldb:9201']


remote_write:
- url: http://squirreldb:9201/api/v1/write
remote_read:
- url: http://squirreldb:9201/api/v1/read
