# Example Prometheus configuration using SquirrelDB as persitent storage

global:
  scrape_interval:     15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['node:9100']
  - job_name: 'squirreldb'
    static_configs:
    - targets: ['squirreldb1:9201', 'squirreldb2:9201']


remote_write:
- url: http://squirreldb:9201/write
# If you want to stress-test SquirrelDB and send much more metrics, uncomment and
# copy/paste this additional remote write and just increment the store01 number for each copy.
#- url: http://squirreldb:9201/write
#  write_relabel_configs:
#  - target_label: job
#    source_labels: ['job']
#    replacement: "store01-$1"

remote_read:
- url: http://squirreldb:9201/read
